module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  allowed_formats: 0
  automated_cron: 0
  bc_aicc: 0
  bc_api_base: 0
  bc_api_docs: 0
  bc_api_logger: 0
  bc_display_title: 0
  bc_sandbox: 0
  big_pipe: 0
  block: 0
  block_content: 0
  bluecadet_alerts: 0
  bluecadet_config_suite: 0
  bluecadet_media_fields: 0
  bluecadet_redirect_importer: 0
  bluecadet_social_links: 0
  bluecadet_text_formats: 0
  bluecadet_utilities: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  components: 0
  config: 0
  config_filter: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  ctools: 0
  date_recur: 0
  date_recur_modular: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  devel_generate: 0
  devel_php: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  embed: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  google_analytics: 0
  help: 0
  history: 0
  hsts: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  key_auth: 0
  kint: 0
  link: 0
  linkit: 0
  media: 0
  media_entity_browser: 0
  menu_block: 0
  menu_ui: 0
  metatag: 0
  metatag_dc: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  node: 0
  options: 0
  page_cache: 0
  pantheon_advanced_page_cache: 0
  path: 0
  path_alias: 0
  queue_ui: 0
  quickedit: 0
  rabbit_hole: 0
  recreate_block_content: 0
  redirect: 0
  redirect_404: 0
  responsive_image: 0
  rh_media: 0
  rh_node: 0
  rh_taxonomy: 0
  save_edit: 0
  scheduler: 0
  search: 0
  shortcut: 0
  simple_block: 0
  simple_sitemap: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  ultimate_cron: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  views_ajax_history: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_config_ignore: 0
  webform_devel: 0
  webform_ui: 0
  workflows: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  longwood: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
